### ISSUE TITLE
Nothing is logged

### ISSUE THREAD

**Issue by SinaBina** [drittich/CloudflareDynDNS#47]
Hi
Thanks for the new release.Although I had my vote on the desktop version :D
I think something is wrong here. I see no log entries in the log section.Is there any configuration to enable it?

![Screenshot 2022-12-22 at 00-29-09 DnsTube v2 0](https://user-images.githubusercontent.com/5496007/209002249-d428656e-46e6-4ead-a461-69994d8f9cb1.png)

Thanks

**Comment by drittich** [comment]
You should see logs, it creates log entries when the service starts up. Just to be sure, try in an incognito browser tab. Is the app functioning otherwise?

**Comment by drittich** [comment]
Also, you can open the developer console, refresh, and see what the log API call returns:
![image](https://user-images.githubusercontent.com/1222810/209003927-85bd3246-2a25-4c0a-955e-1103e32b6f42.png)

**Comment by drittich** [comment]
>Although I had my vote on the desktop version 
I might rebuild the desktop version, as well as a command-line one. Wanted to start with web since service was a priority for me.

**Comment by SinaBina** [comment]
Thanks for reply.
I figured it out.I use uBlock Ad-blocker extension with my Firefox. Disabled it and I can see the entire log.
Thanks

**Comment by drittich** [comment]
@SinaBina It looks like uBlock blocks API calls named `log`. I fixed by renaming in commit https://github.com/drittich/DnsTube/commit/4d357c3c6d377c2f68e97055f92fae8539a8a170. The next release will have this fix.

**Comment by SinaBina** [comment]
Thanks
