### ISSUE TITLE
Service cant start Error: 1053

### ISSUE THREAD

**Issue by LunayderKater** [drittich/CloudflareDynDNS#48]
What i do:
1) Put everything from the zip into a folder.
2) Open CMD.exe as administartor
3) go to that folder.
4) use: install-service.bat

Log:
D:\CF Updater>install-service.bat
Creating service...
[SC] CreateService ERFOLG
[SC] ChangeServiceConfig2 ERFOLG
Starting service...
[SC] StartService FEHLER 1053:

Der Dienst antwortete nicht rechtzeitig auf die Start- oder Steuerungsanforderung.
(The Service dosnt respond in time to start or control requests.)

**Comment by drittich** [comment]
I think you'll need to install .NET 7: https://dotnet.microsoft.com/en-us/download/dotnet/7.0

**Comment by drittich** [comment]
Let me know if you have any further issues.

**Comment by LunayderKater** [comment]
Installing .Net 7.1 fixed the issue. (maybe including a error message at the setup instead of the generic "cant start service" would have helped me ^^)

**Comment by drittich** [comment]
The latest installer should do this.
