### ISSUE TITLE
Malformed response, expected IP

### ISSUE THREAD

**Issue by thegrassjelly** [drittich/CloudflareDynDNS#51]
![image](https://user-images.githubusercontent.com/46816744/218249584-6c5794e8-0455-4fbd-ac2f-33affabb320f.png)

Hello just started setting this up, im not sure if its related with the error log but in the Public IP field empty

![image](https://user-images.githubusercontent.com/46816744/218249666-f0fe8802-c006-47cd-9439-d2c9b55725b0.png)

But when inspecting the element, there seems to be a value populated, just not in the actual UI.

**Comment by drittich** [comment]
It's complaining because the value coming back from the API used to determine your IP address can't be parsed. I'm suspecting it might be wrapped in HTML tags. What IPv4 API do you have configured in settings? Can you hit the API directly and paste the response here?

**Comment by thegrassjelly** [comment]
Thank you for the quick response, just stupid mistake in my end. I thought the IPv4 API fields was for my hostname registered to Cloudflare, I changed it to https://api.ipify.org and its now working!
