### ISSUE TITLE
Can not retrieve public IP

### ISSUE THREAD

**Issue by Denvy-Shi** [drittich/CloudflareDynDNS#52]
As captured below, my instance cannot retrieve the public IP and as a result, the DNS records are not updated.
I installed it as a Windows service with Administrator privilege.
Any advice?
![image](https://user-images.githubusercontent.com/86651444/223358640-38a91784-aff6-4a5f-9a3c-3d5c047c90a9.png)

**Comment by Denvy-Shi** [comment]
Invalid setting of ip API at my side.

**Comment by tungnb** [comment]
> Invalid setting of ip API at my side.

I got the same problem. What did you setting? Please help me to solve. Thanks
![Capture](https://github.com/drittich/DnsTube/assets/5979923/22d84239-6b5e-4e58-837d-a6e44ca42df2)

**Comment by drittich** [comment]
Can you load the API URL in your browser successfully?

**Comment by tungnb** [comment]
> Can you load the API URL in your browser successfully?

Yes, I can
This is problem when I tried to use old version

> 2023-07-19 07:38:07: Error getting public IPv4: The SSL connection could not be established, see inner exception.
> 2023-07-19 07:38:07: Error detecting public IPv4 address

**Comment by drittich** [comment]
Thanks, that's helpful. I think I can resolve this, I'll take a look and create a new issue for this.

**Comment by drittich** [comment]
@tungnb Comment on this issue so you can get updates: https://github.com/drittich/DnsTube/issues/57

**Comment by drittich** [comment]
> This is problem when I tried to use old version

@tungnb  I just noticed your comment above. What version of DnsTube are you running to produce the error?

**Comment by tungnb** [comment]
> > This is problem when I tried to use old version
> 
> @tungnb I just noticed your comment above. What version of DnsTube are you running to produce the error?

Hi,
I used v2.2 but cannot get the IP. So I open v0.9.10. This error noticed from v0.9.10.
Thank you

**Comment by drittich** [comment]
@tungnb Thanks, please continue discussion in https://github.com/drittich/DnsTube/issues/57

**Comment by drittich** [comment]
@Denvy-Shi @tungnb Please let me know what version of Windows you are using.
