### ISSUE TITLE
Unable to use with a VPN split tunnel

### ISSUE THREAD

**Issue by kgtree** [drittich/CloudflareDynDNS#54]
VPN ip address is fetched instead of ISP ip address

**Comment by drittich** [comment]
Thanks for the feedback. If I understand your issue correctly, you want to be able to choose what adapter is used for the request to determine the public IP address so that you can decide whether it uses the VPN or not. This is doable - I will try to find some time in the near future, but happy to accept a pull request as well.

**Comment by arjunsrinivasan1997** [comment]
I would really appreciate this feature as well.

**Comment by arjunsrinivasan1997** [comment]
@kgtree I found a workaround though it does require your VPN app to have the ability to bypass websites. If you add IPv4 API and IPv6 API urls as ones that should be bypassed by your VPN, DNS tube will get the proper IP address to update your DNS records with.

**Comment by kgtree** [comment]
@arjunsrinivasan1997 I appreciate the tip, unfortunately my VPN only allows split tunneling for apps and IP addresses

**Comment by drittich** [comment]
I'm going to resolve this soon, just have a few things to consider.

**Comment by drittich** [comment]
I've got a beta release out that supports this, see https://github.com/drittich/DnsTube/releases/tag/v2.4.0-beta

@kgtree @arjunsrinivasan1997 Please give it a try when you can and let me know if you have any issues.

**Comment by arjunsrinivasan1997** [comment]
@drittich Thanks for your work on this so far. I'm currently out of town so don't want to tweak my config but will test it when I get back.

**Comment by kgtree** [comment]
@drittich Thanks for working on this beta to provide this feature. However, I can't seem to get the the drop down menu to populate with an adapter to choose. I've tried restarting the dnstube service, restarting my VPN, and restarting my PC to no avail.

**Comment by drittich** [comment]
In the code I'm filtering for adapters that have an operational status of
"Up" and maybe that's not a reliable thing to do. Give me a little bit, and
I'll create another release without that filter, and we'll see what comes
back.

**Comment by drittich** [comment]
@kgtree Try this updated beta release: https://github.com/drittich/DnsTube/releases/tag/v2.4.0-beta2

**Comment by kgtree** [comment]
@drittich Unfortunately the same issue persists with beta 2

**Comment by drittich** [comment]
@kgtree What is the response from this URL: http://localhost:5666/api/settings/adapters

**Comment by kgtree** [comment]
@drittich I receive the following: No webpage was found for the web address: http://localhost:5666/api/settings/adapters
HTTP ERROR 404

**Comment by drittich** [comment]
@kgtree  Maybe you are using a different port? Are you using the standard installation port? What version does the app say you are running (check the log)?

**Comment by kgtree** [comment]
@drittich So sorry! I didn't stop and reinstall the service as administrator so I was still running version 2.1 even though the webui said I was running 2.4 at the top. I've enabled my ethernet adapter and I'm now pulling my isp ip instead of my vpn ip address. Thank you for helping me troubleshoot that.

**Comment by drittich** [comment]
Glad to help!
