### ISSUE TITLE
install-service.bat requires .NET 7 SDK, could be .NET 7 runtime only

### ISSUE THREAD

**Issue by tifish** [drittich/CloudflareDynDNS#56]
Change the checking line to:

```bat
dotnet --list-runtimes | findstr /C:" 7."
```

**Comment by drittich** [comment]
Thanks for the feedback, will take a look.

**Comment by FrAllard** [comment]
I tried it... It will install the service with only the runtime, but the service need the sdk to start, so... sdk is required!

**Comment by drittich** [comment]
I'll try to figure out what that dependency is.

**Comment by drittich** [comment]
@FrAllard  I just tried on a new Windows 7 install, and just the runtime worked for me. I was able to start the service and load the web UI. What was the behaviour you were seeing?

**Comment by drittich** [comment]
Closing, can't reproduce.
