### ISSUE TITLE
send the intranet address to the domain name

### ISSUE THREAD

**Issue by maomaochong199** [drittich/CloudflareDynDNS#58]
to convenient for the computers on the intranet to be remote from each other, how to set it up

**Comment by drittich** [comment]
I'm not able to understand your question. Can you explain more?

**Comment by maomaochong199** [comment]
I have achieved my goal by modifying this bat   。

https://github.com/dcerisano/cloudflare-dynamic-dns/blob/master/cloudflare-ddns.bat  

I want to convert the intranet address to a domain name, because the intranet ip under the router will also change

Your webui does not have the function of uploading the intranet address to the domain name

**Comment by drittich** [comment]
That is the exactly the function of DnsTube - but glad you found a solution that works for you!
