### ISSUE TITLE
Still cannot update IP

### ISSUE THREAD

**Issue by teglafal** [drittich/CloudflareDynDNS#59]
After updating to the new version, there are still issues with updating my IP:

[System.Net](http://system.net/).Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> [System.Security](http://system.security/).Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'. ---> [System.ComponentModel.Win](http://system.componentmodel.win/)32Exception (0x80090326): A kapott üzenet váratlan vagy rosszul formázott --- End of inner exception stack trace --- at [System.Net.Security](http://system.net.security/).SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken) at [System.Net](http://system.net/).Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken) --- End of inner exception stack trace --- at [System.Net](http://system.net/).Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken) at [System.Net](http://system.net/).Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at [System.Net](http://system.net/).Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at [System.Net](http://system.net/).Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at [System.Net](http://system.net/).Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken) at [System.Net](http://system.net/).Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at [System.Net](http://system.net/).Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at [System.Net](http://system.net/).Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken) at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken) at [System.Net](http://system.net/).Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) at [DnsTube.Core.Services](http://dnstube.core.services/).IpAddressService.GetPublicIpAddressAsync(IpSupport protocol)

**Comment by drittich** [comment]
What is the URL you are using to get your public IP address? I'm looking for the entries in this section of settings:
![image](https://github.com/drittich/DnsTube/assets/1222810/15a2050b-5a3c-46f0-9ec0-7d681818aea3)

Also, please let me know what version of Windows you are using.

**Comment by teglafal** [comment]
I think it's the same:
![kép](https://github.com/drittich/DnsTube/assets/146929983/be0e7a59-d76c-4773-9a5f-47d6b9b4a8b3)

OS: Windows 7 SP1 x64

**Comment by drittich** [comment]
OK, I think that's the root cause. Please try this update: [Update to enable TLS 1.1 and TLS 1.2 as default secure protocols in WinHTTP in Windows - Microsoft Support](https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392)

**Comment by teglafal** [comment]
It's the same. The update was installed already, so I just created all the reg entries, but nothing has changed..

**Comment by drittich** [comment]
There is an Easy Fix Tool mentioned here that may help: [Authentication errors when client doesn't have TLS 1.2 support - SharePoint | Microsoft Learn](https://learn.microsoft.com/en-us/sharepoint/troubleshoot/administration/authentication-errors-tls12-support#windows-8-windows-7-or-windows-server-20122008-r2sp1)

**Comment by teglafal** [comment]
Tried with the EasyFix too, I can see the reg key its created, but the issue is the same.

**Comment by drittich** [comment]
Give me a bit, I'll see if I can repro with a Win 7 virtual machine.

**Comment by teglafal** [comment]
Okay, thank You very much! I know I should move on from Windows 7 btw, but sometimes it's very very hard to reinstall a system which is basically perfectly configured for my every day use...
(btw if I have a little time, I'll test it out on a virtual Windows 10 with the same config I am using now to see the results)

**Comment by drittich** [comment]
OK, I reproduced the problem and did some testing. The situation is that Windows 7 is missing some newer cipher suites that it will never receive via OS updates due its age. (The browsers handle cyphers themselves which is why they work, but apps making HTTP calls may fail.)

The workaround is to update your settings to use another end point for IP address detection that uses different cyphers. E.g., I tried https://api.seeip.org/ to get my IPv4 public address on Windows 7 and it worked fine.

![image](https://github.com/drittich/DnsTube/assets/1222810/f968d773-4186-4d93-ba61-9a8798736a8f)

**Comment by teglafal** [comment]
Thank You very much, You are the man, works like charm!

**Comment by PaperPlaneDeemo** [comment]
> OK, I reproduced the problem and did some testing. The situation is that Windows 7 is missing some newer cipher suites that it will never receive via OS updates due its age. (The browsers handle cyphers themselves which is why they work, but apps making HTTP calls may fail.)好的，我重现了问题并做了一些测试。情况是 Windows 7 缺少了一些较新的密码套件，而由于年久失修，它永远无法通过操作系统更新获得这些密码套件。(浏览器会自行处理密码，这就是为什么它们能正常工作，但进行 HTTP 调用的应用程序可能会失败）。
> 
> The workaround is to update your settings to use another end point for IP address detection that uses different cyphers. E.g., I tried https://api.seeip.org/ to get my IPv4 public address on Windows 7 and it worked fine.解决方法是更新设置，使用另一个使用不同密文的 IP 地址检测终端。例如，我曾尝试在 Windows 7 上使用 https://api.seeip.org/ 获取 IPv4 公共地址，效果很好。
> 
> ![image](https://private-user-images.githubusercontent.com/1222810/272772617-f968d773-4186-4d93-ba61-9a8798736a8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzM4NTMsIm5iZiI6MTcxMzUzMzU1MywicGF0aCI6Ii8xMjIyODEwLzI3Mjc3MjYxNy1mOTY4ZDc3My00MTg2LTRkOTMtYmE2MS05YTg3OTg3MzZhOGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMTMzMjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRiZmVhNWY1NmNkMjllNzhjZGY4ZGFkZDgxOWNiZGEyOWVmYWUwOGZmZDE2NGYyZWE4MjNjOGU5YWJiMzI3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.M2tLdFVW9NitO8mXl238qJpP6E59xAr95uCT3o9idSU)

Everything was normal until today, but now the original API cannot retrieve the IP after I started using a proxy server. My windows version is Windows Server 2022 Standard and I'm using v2.5.0. I have the same issue above. The log said "The SSL connection could not be established, see inner exception." when i use "https://api.ipify.org/". And I change it to https://api.seeip.org/  everything works well.
