### ISSUE TITLE
.NET 8 Beta Install Script Expects .NET 7

### ISSUE THREAD

**Issue by jacobslusser** [drittich/CloudflareDynDNS#71]
I'm testing the new [DnsTube v2.8.0-beta](https://github.com/drittich/DnsTube/releases/tag/v2.8.0-beta) builds and it looks like the `install-service.bat` script is still checking for .NET 7 instead of .NET 8. 

[DnsTube.Service/install-service.bat](https://github.com/drittich/DnsTube/blob/7da4562507e5eb023c57f4218702d576bb9ee72b/DnsTube.Service/install-service.bat#L7-L15)
```batch
rem check that .NET 7 SDK is installed
dotnet --list-sdks | findstr /C:7. /B
if %ErrorLevel% equ 0 (
    echo Found .NET 7 SDK
) else (
    echo .NET 7 SDK not installed, please download and install from https://dotnet.microsoft.com/en-us/download/dotnet/7.0
	echo Exiting
	goto :eof
)
```

Screenshot
![image](https://github.com/user-attachments/assets/d2022948-c447-49de-9096-c617b81b815f)

**Comment by drittich** [comment]
Thanks, I missed that. Should be fixed within 24 hours.

**Comment by drittich** [comment]
Give this release a try: https://github.com/drittich/DnsTube/releases/tag/v2.8.0-beta2

**Comment by FlattusBlastus** [comment]
Still in 2.7.1

**Comment by drittich** [comment]
@FlattusBlastus v2.7.1 is a .NET 7 version.
