### ISSUE TITLE
After error, the service doesn't update anymore

### ISSUE THREAD

**Issue by XHead-git** [drittich/CloudflareDynDNS#72]
![image](https://github.com/user-attachments/assets/e9ed313e-5ca3-4340-a11a-f86e4d8290cf)

When there is an error, the service does not try to update the IP anymore.
This is a common error, because when the network was down due to IP change, it may take a while for the internet do be up, and the service will error because it can't reach the internet. Only a manual update can solve the problem. Can you add a retry on error interval ?
I'm using DnsTube version 2.7.

**Comment by drittich** [comment]
Thanks for the report, this is obviously not desired behavior. I'll take a look ASAP.

**Comment by drittich** [comment]
This should be resolved with [Release v2.7.1](https://github.com/drittich/DnsTube/releases/tag/v2.7.1). 

Note that this will retry at the next scheduled update interval. A future release will add immediate retries on error.
